### PR TITLE
Fix: global backaddr is assumed to be static #84

### LINKED ISSUE #84: global backaddr is assumed to be static
hi :-)

when configuring a hostname for a backend the hostname is only resolved once in `init_globals`.
=>
in a way, hitch acts as a DNS cache that doesn't respect TTL.

related use case: using amazon ELB as backend.

possible solution: register an event to refresh the cached value of `backaddr` when the DNS value expires.

### PR DESCRIPTION
**Pull request by dmatetelki**
Fixes #84 and #214

### CODE REVIEW

File: src/hitch.c [hunk 1]
```diff
@@ -1930,6 +1950,17 @@ static void end_handshake(proxystate *ps) {
...
 			write_ip_octet(ps);
 		}
+
+		int back = create_back_socket();
+		if (back == -1) {
+			ERR("{backend-socket}: %s\n", strerror(errno));
+			return;
+		}
+		ps->fd_down = back;
+		ev_io_init(&ps->ev_w_connect, handle_connect, back, EV_WRITE);
```
Comment (dmatetelki) [inline src/hitch.c]: this 3 relocated lines needs to be invertigated

File: src/tests/test25-dynamic-backend-address.sh [hunk 2]
```diff
@@ -0,0 +1,34 @@
+#!/bin/sh
+
+. hitch_test.sh
+set +o errexit
+
+echo "hitch_test hitch-tls.org" > /tmp/hitch_hosts
```
Comment (Dridi) [inline src/tests/test25-dynamic-backend-address.sh]: `mktemp -d` for directories, with #209 you can safely use your current directory.

File: src/tests/test25-dynamic-backend-address.sh [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+export HOSTALIASES=/tmp/hitch_hosts
```
Comment (Dridi) [inline src/tests/test25-dynamic-backend-address.sh]: May only work with glibc.
